"use strict";

const LINE_COPILOT_CONFIG = Object.freeze({
  API_BASE_URL: "",
  USE_MOCK_API: true,
  REQUEST_TIMEOUT_MS: 30000,
  MAX_VISIBLE_MESSAGES: 5
});

globalThis.LINE_COPILOT_CONFIG = LINE_COPILOT_CONFIG;
